CREATE TABLE BOOK (
  ID INT NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(60) NOT NULL ,
  YEAR INT NOT NULL,
  PAGES_COUNT INT,
  CREATED_AT DATE,                -- for demonstrating purposes only (@Temporary)
  VERSION INT NOT NULL DEFAULT 0, -- for optimistic concurrency      (@Version)
  PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR (
  ID INT NOT NULL AUTO_INCREMENT ,
  FIRST_NAME VARCHAR(60) NOT NULL ,
  LAST_NAME VARCHAR(60) NOT NULL ,
  UNIQUE (FIRST_NAME, LAST_NAME),

  PRIMARY KEY (ID)
);

CREATE TABLE TELEPHONE (
  AUTHOR_ID INT NOT NULL ,
  TEL VARCHAR(60) NOT NULL ,
  PRIMARY KEY (TEL),

  CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE
);



CREATE TABLE BOOK_AUTHOR_REF (
  BOOK_ID INT NOT NULL ,
  AUTHOR_ID INT NOT NULL ,
  PRIMARY KEY (BOOK_ID, AUTHOR_ID),

  CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ,
  CONSTRAINT FK_AUTHORREF FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);