INSERT INTO ARTICLE (ID, NAME, DESCRIPTION) VALUES (1, 'ARTICLE TEST', 'MY FIRST ARTICLE');
INSERT INTO ARTICLE (ID, NAME, DESCRIPTION) VALUES (2, 'AUTO', 'MY AUTO ARTICLE');
INSERT INTO ARTICLE (ID, NAME, DESCRIPTION) VALUES (3, 'ROBOT TEST', 'MY ROBOT ARTICLE');
INSERT INTO ARTICLE (ID, NAME, DESCRIPTION) VALUES (4, 'TV TEST', 'MY TV ARTICLE');
INSERT INTO ARTICLE (ID, NAME, DESCRIPTION) VALUES (5, 'BALL TEST', 'MY BALL ARTICLE');